### ISSUE TITLE
Generate bounding boxes for labeler

### ISSUE THREAD

**Issue by lukeforehand** [lukeforehand/deertracker#1]
```
 ./dt import-photos \
    --photos myphotos/  \
    --training
```

* `--training` flags the photos as training data.

### Caltech camera traps:
http://lila.science/datasets/caltech-camera-traps
```
~/Downloads/azcopy_linux_amd64_10.7.0/azcopy cp \
"https://lilablobssc.blob.core.windows.net/caltech-unzipped/cct_images?st=2020-01-01T00%3A00%3A00Z&se=2034-01-01T00%3A00%3A00Z&sp=rl&sv=2019-07-07&sr=c&sig=uNGA5/QrgqpnU4VeT5tBqhx0GN4Tu8jJ7neUyJqIQss%3D" \
. --recursive
```

### Wisconsin whitetail deer data set
```
https://drive.google.com/drive/folders/1jjkIPjz0Mv3ETYhafE4maNvtBfAxgRsW?usp=sharing
https://drive.google.com/drive/folders/1E1bVtDpXvgYpXbO5jpYDV37TYc9sUp2C?usp=sharing
https://drive.google.com/drive/folders/1ihIpAar8G2kFvC2jOwJFA9GAUSGwT1Tb?usp=sharing
https://drive.google.com/drive/folders/0B4BRcQQjVlWyVnctaE84Y3dHcDQ?usp=sharing
https://drive.google.com/drive/folders/0B4BRcQQjVlWyVXNMeHJ4LTdJV2c?usp=sharing
```

**Comment by lukeforehand** [comment]
See CalTech camera trap dataset

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lukeforehand** [comment]
I don't recommend trying to download the 100GB zip file, network failures often.  Alternative method is to grab the unzipped photos directly off their Azure storage:

```
~/Downloads/azcopy_linux_amd64_10.7.0/azcopy cp "https://lilablobssc.blob.core.windows.net/caltech-unzipped/cct_images?st=2020-01-01T00%3A00%3A00Z&se=2034-01-01T00%3A00%3A00Z&sp=rl&sv=2019-07-07&sr=c&sig=uNGA5/QrgqpnU4VeT5tBqhx0GN4Tu8jJ7neUyJqIQss%3D" . --recursive
```

**Comment by lukeforehand** [comment]
There's only bounding boxes for 66k out of 240k so I'm extracting those images out of the dataset:
```
caltech_bboxes_20200316.json
112:   "image_id": "588a679f-23d2-11e8-a6a3-ec086b02610b",

caltech_images_20200316.json
2025383:   "file_name": "test/588a679f-23d2-11e8-a6a3-ec086b02610b.jpg",
3093843:   "image_id": "588a679f-23d2-11e8-a6a3-ec086b02610b"
```

**Comment by lukeforehand** [comment]
We can also split out the data into categories using `category_id`.  The dataset isn't split out by class, only training / test.

**Comment by lukeforehand** [comment]
I just committed code that crops the caltech dataset, takes about 1.5 hours to complete single threaded.

show bboxes
```
./dt caltech --show
```

create crops
```
./dt caltech
```

**Comment by lukeforehand** [comment]
I added a labeling tool to the project with instructions:
https://github.com/lukeforehand/deertracker/blob/main/README.md#labeling-tool

@kbrose I will be labeling crops from my whitetail dataset and caltech starting tomorrow! :-)  I'm adding 10 pixels or 1% to height and width to the crop based on your specifications. :-)

**Comment by kbrose** [comment]
I'm downloading the caltech data myself right now, should be able to run your cropping code today or tomorrow. My goal is to have a simple species classifier training today or tomorrow. The main problem is disk space for me. My laptop has room but not my desktop (with the GPU). I might have to downsize the dataset to begin the training.

**Comment by lukeforehand** [comment]
- Sounds great, I went looking for my GPU machine and realized I sold it a few years back 🤣.  Might have to get a new one 😁.
Btw When you run the CalTech crop entry point it puts the database and photos under deer tracker/.data/

**Comment by lukeforehand** [comment]
I have those crops if you want to save space, 2.4GB total

**Comment by kbrose** [comment]
Wow that's super small. Yeah if you wouldn't mind just sharing those + the DB (unless that's easy to generate myself) that'd be great

**Comment by lukeforehand** [comment]
https://github.com/lukeforehand/deertracker/blob/main/NOTES.md#caltech-crops
^ Has the link to the crops and the species distribution.

Shortcut:
crops:
https://drive.google.com/file/d/1w637_EcV637L8TxfWdcm6WmEvmBh480G/view?usp=sharing

db:
https://drive.google.com/file/d/10HlUBEe06nGMc8MxvZBw1InO2Kvri86H/view?usp=sharing

**Comment by kbrose** [comment]
> Might have to get a new one 😁.

If you do, take note that most frameworks just support nvidia graphics cards, and if they do support AMD it's definitely a second class citizen. But I think google colab will probably work well for this project

**Comment by lukeforehand** [comment]
Btw make sure and pull main the .data folder moved out of deertracker/ and into the root of the project.  Models/ also modes to root

**Comment by lukeforehand** [comment]
Made a markdown file tracking dataset progress.  Latest is I've curated the "whitetail" crops and now need to label them.

**Comment by lukeforehand** [comment]
https://github.com/lukeforehand/deertracker/blob/main/docs/DATASETS.md
