### ISSUE TITLE
Combine trained classifier with megadetector

### ISSUE THREAD

**Issue by lukeforehand** [lukeforehand/deertracker#16]

**Comment by lukeforehand** [comment]
@kbrose do we have to do this after the classifier is sufficiently trained?

**Comment by kbrose** [comment]
I'm not sure what you mean by combine them.

It's totally valid to run the megadetector to get bounding boxes, and then pass in the crops to the classifier model.

**Comment by lukeforehand** [comment]
Oh ok I was not understanding, I thought the detector had a last step for classification we were replacing.  I'm totally cool with the approach your mentioning!

**Comment by kbrose** [comment]
Yeah good point, we should only take the animal bounding boxes from the megadetector, not the person/vehicle classes.
