### ISSUE TITLE
Ability to resume classifier training

### ISSUE THREAD

**Issue by lukeforehand** [lukeforehand/deertracker#22]
Google colab is saving models to google drive, but the notebook has plenty of disconnect problems so I would like to pass an option to the `train` command `--resume`.  I imagine it won't be that difficult to add this feature to the train function.  @kbrose Do you think I can handle that ?

**Comment by lukeforehand** [comment]
https://www.tensorflow.org/tutorials/keras/save_and_load

**Comment by kbrose** [comment]
I can take a look at it. It can actually be tricky to get right as there's a lot of hidden state during training that needs to get persisted correctly. E.g. the `optimizer` can be a stateful object and if its state isn't persisted, then resuming can catastrophically effect performance.

**Comment by lukeforehand** [comment]
I'll take a look at the PR !  Were you able to side-step the catastrophic effects?  :-D

**Comment by kbrose** [comment]
I believe so, thankfully they've made this easier than when I was using TF1.x (for some small x)
