### ISSUE TITLE
Don't necessarily need to take buffer around bbox during inference

### ISSUE THREAD

**Issue by kbrose** [lukeforehand/deertracker#25]
Looking at https://github.com/lukeforehand/deertracker/blob/main/deertracker/model.py#L14-L22 -- we don't necessarily need to add this buffer around images during inference.

I added the buffer in during training because we also take a random crop during training (to try and make the classifier more robust to bad crops). I doubt it would change much either way, but I thought I'd put a note in just in case.

**Comment by lukeforehand** [comment]
Ok, good to know.  I think it ended up being in here because I was planning on using all crops saved during inference for use in further labeling and training.

**Comment by lukeforehand** [comment]
This is addressed in grpc branch merge; the padding is only added to crops saved for training, not during inference.  See deertracker.model.Detector
