### ISSUE TITLE
Find a server for trail cam media

### ISSUE THREAD

**Issue by lukeforehand** [lukeforehand/deertracker#4]
I have trail camera photos and videos all the way back from 2014 that need to be shared with any collaborators that wish to perform labeling or run training.

Some of the data is currently here for download:

https://drive.google.com/drive/folders/1jjkIPjz0Mv3ETYhafE4maNvtBfAxgRsW?usp=sharing
https://drive.google.com/drive/folders/1E1bVtDpXvgYpXbO5jpYDV37TYc9sUp2C?usp=sharing
https://drive.google.com/drive/folders/1ihIpAar8G2kFvC2jOwJFA9GAUSGwT1Tb?usp=sharing
https://drive.google.com/drive/folders/0B4BRcQQjVlWyVnctaE84Y3dHcDQ?usp=sharing
https://drive.google.com/drive/folders/0B4BRcQQjVlWyVXNMeHJ4LTdJV2c?usp=sharing

**Comment by lukeforehand** [comment]
@kbrose I’m downloading the big dataset above to an external drive, and I have a weeks worth of photos from three cams in my woods I will keep to the side for when we want to test the (unwritten) tracking software.  I’ll also dl the dataset CalTech used

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lukeforehand** [comment]
Processing about 100 photos per hour on a 4 core machine, no gpu.

**Comment by kbrose** [comment]
Awesome. LMK the best way for me to get the processed images. I don't have a ton of room left on any of my drives, but I was planning on ordering a new drive anyway, so I should have room soon.

**Comment by lukeforehand** [comment]
I am going to sift through the crops from my cousins whitetail dataset removing some non-trap crops (I see I processed some non trap photos).  Then I was gonna start labeling them, and I can put the results on google drive for you hopefully the archive won't be huge, it will for sure be less than 4GB.

I was going to use the CalTech species classes and add a few if that's alright, like bear, coyote wolf and owl (rare).  Also was going to add doe, spike, 4-6 pt, and 8-12 pt buck since his dataset is basically deer turkeys and beer.  We could also train with caltech and I could further extract deer crops specifically and relabel them with the deer specific classes.  Let me know if any of this sounds infeasible.
