### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by lukeforehand** [lukeforehand/deertracker#6]
Agree along with collaborators on a software license.

**Comment by kbrose** [comment]
I'd be fine with most open source licenses. I usually do MIT for my stuff, but I'd also be ok with a more aggressive one like GPL if that's what you were thinking.

**Comment by lukeforehand** [comment]
Ok great I chose AGPLv3 
https://github.com/lukeforehand/deertracker/blob/main/LICENSE
